### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ghost** [51Degrees/ua-parser-js#1]
In the "User-Agent Client Hints delegation" section of the readme file, the example Accept-CH header has a typo. the `Sec-CH-Bitness` should read `Sec-CH-UA-Bitness`
`Accept-CH: Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-Bitness,`

Does this mistake appear anywhere else in the package, or is it just the readme file?

**Comment by justadreamer** [comment]
Hi @kirstin51D thank you for reporting.  This typo only appeared in the README file: 
```sh
grep -R "Sec-CH-Bitness"
./README.md:  ch = 'Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-Bitness, Sec-CH-UA-Full-Version, \
./README.md:Accept-CH: Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, 
```

Fixed
